/*%macro test_month(orgcode,startdate,enddate);*/
options compress=yes mprint mlogic noxwait NOQUOTELENMAX;                                                                                                                                                                                                       
libname nfcs oracle user=datauser password=zlxdh7jf path=p2p;
%include "E:\新建文件夹\SAS\常用代码\自动化\000_FORMAT.sas";
%include "E:\新建文件夹\SAS\基础宏.sas";

/*报送记录数*/
proc sql noprint;
        select sum(itotalcount),sum(isuccesscount) into :itotalcount_temp :itotalcount_temp
        from nfcs.Sino_msg(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                      
;
quit;	
                                                                                                                                                                                                                                                                
/*个人基本信息*/                                                                                                                                                                                                                                                
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :sf_count_temp                                                                                                                                                                                                           
        from nfcs.Sino_person(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                                    
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*贷款业务信息*/                                                                                                                                                                                                                                                
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :loan_count_temp                                                                                                                                                                                                         
        from nfcs.Sino_loan(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                                      
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*贷款申请信息*/                                                                                                                                                                                                                                                
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :sq_count_temp                                                                                                                                                                                                           
        from nfcs.Sino_loan_apply(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                                
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*特殊交易信息*/                                                                                                                                                                                                                                                
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :spec_count_temp                                                                                                                                                                                                         
        from nfcs.Sino_loan_spec_trade(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                           
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*贷款合同信息*/                                                                                                                                                                                                                                                
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :hetong_count_temp                                                                                                                                                                                                       
        from nfcs.sino_loan_compact(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                              
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*担保信息*/                                                                                                                                                                                                                                                    
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :guar_count_temp                                                                                                                                                                                                         
        from nfcs.sino_loan_guarantee(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                            
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*投资信息*/                                                                                                                                                                                                                                                    
proc sql noprint;                                                                                                                                                                                                                                               
        select count(*) into :invest_count_temp                                                                                                                                                                                                       
        from nfcs.Sino_loan_investor(where = (sorgcode = "&orgcode." and &startdate. < datepart(dgetdate) < &enddate.))                                                                                                                             
;                                                                                                                                                                                                                                                               
quit;                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                
/*%put x = &sf_count_temp.;                                                                                                                                                                                                                             */
/*%put x = &loan_count_temp.;                                                                                                                                                                                                                           */
/*%put x = &sq_count_temp.;                                                                                                                                                                                                                             */
/*%put x = &spec_count_temp.;                                                                                                                                                                                                                           */
/*%put x = &guar_count_temp.;                                                                                                                                                                                                                           */
/*%put x = &invest_count_temp.;                                                                                                                                                                                                                         */
/*%put x = &hetong_count_temp.;                                                                                                                                                                                                                         */
/*总计*/                                                                                                                                                                                                                                                        
%let total_count_temp = %sysfunc(sum(&sf_count_temp. , &loan_count_temp. , &sq_count_temp. , &spec_count_temp. , &guar_count_temp. , &invest_count_temp. , &hetong_count_temp.))
/*%put &total_count_temp.;                                                                                                                                                                                                                              */
                                                                                                                                                                                                                                                                
%let content = %sysfunc(compress(%str(自2015年6月1日起，至2015年6月30日，)%str(上海嘉银金融服务有限公司)
%str(共计报送数据)&itotalcount_temp.%str(条，其中成功入库数据)&itotalcount_temp.%str(条。)
%str(共计成功入库数据)&total_count_temp.%str(条。其中，借款人信息)                                                                                                                                                                                                          
&sf_count_temp.%str(条，贷款业务信息)&loan_count_temp.%str(条，贷款申请信息）                                                                                                                                                              
&sq_count_temp.%str(条，特殊交易信息)&spec_count_temp.%str(条，担保信息）                                                                                                                                                                  
&guar_count_temp.%str(条，投资信息）&invest_count_temp.%str(条)));                                                                                                                                                                          
                                                                                                                                                                                                                                                                
/*%put &content.;                                                                                                                                                                                                                                                 */

%mend; 


%test_month(Q10155800HS000,MDY(6,1,2015),MDY(6,30,2015));

