

%MACRO AREA_ANALYSIS(STAT_DT);

%LET LAST_DT=INTNX('MONTH',&STAT_DT.,-1,'END');
/*T-1月数据处理*/
/*贷款信息*/
PROC SORT DATA=SSS.SINO_LOAN(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &STAT_DT.))  OUT=LOAN_N1 ;
	BY SORGCODE SACCOUNT DGETDATE;
RUN;
DATA LOAN_N2;
	SET LOAN_N1;
	BY SORGCODE SACCOUNT DGETDATE;
	IF LAST.SACCOUNT;
RUN;
DATA LOAN_N;
	SET LOAN_N2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*申请信息*/
PROC SORT DATA=SSS.SINO_LOAN_APPLY(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &STAT_DT.)) OUT= APPLY_N1;
	BY SORGCODE SAPPLYCODE SCERTNO;
RUN;
DATA APPLY_N2;
	SET APPLY_N1;
	BY SORGCODE SAPPLYCODE SCERTNO;
	IF LAST.SCERTNO;
RUN;
DATA APPLY_N;
	SET APPLY_N2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*特殊交易信息*/
PROC SORT DATA=SSS.Sino_LOAN_SPEC_TRADE(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &STAT_DT.)) OUT=SPEC_N1;
	BY SORGCODE SACCOUNT;
RUN;
DATA SPEC_N2;
	SET SPEC_N1;
	BY SORGCODE SACCOUNT;
	IF LAST.SACCOUNT;
RUN;
DATA SPEC_N;
	SET SPEC_N2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*T-2月数据处理*/
/*贷款信息*/
PROC SORT DATA=SSS.SINO_LOAN(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &LAST_DT.))  OUT=LOAN_O1 ;
	BY SORGCODE SACCOUNT DGETDATE;
RUN;

DATA LOAN_O2;
	SET LOAN_O1;
	BY SORGCODE SACCOUNT DGETDATE;
	IF LAST.SACCOUNT;
RUN;
DATA LOAN_O;
	SET LOAN_O2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*申请信息*/
PROC SORT DATA=SSS.SINO_LOAN_APPLY(WHERE=(SUBSTR(SORGCODE,1,1)='Q'  AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &LAST_DT.)) OUT= APPLY_O1;
	BY SORGCODE SAPPLYCODE SCERTNO;
RUN;

DATA APPLY_O2;
	SET APPLY_O1;
	BY SORGCODE SAPPLYCODE SCERTNO;
	IF LAST.SCERTNO;
RUN;
DATA APPLY_O;
	SET APPLY_O2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*特殊交易信息*/
PROC SORT DATA=SSS.Sino_LOAN_SPEC_TRADE(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND SORGCODE not in ('Q10152900H0000' 'Q10152900H0001') AND DATEPART(DGETDATE) <= &LAST_DT.)) OUT=SPEC_O1;
	BY SORGCODE SACCOUNT;
RUN;
DATA SPEC_O2;
	SET SPEC_O1;
	BY SORGCODE SACCOUNT;
	IF LAST.SACCOUNT;
RUN;
DATA SPEC_O;
	SET SPEC_O2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*T-1月综合数据处理*/

PROC SQL;
	CREATE TABLE LOANAREA_N AS SELECT
		A1.ORGAREA LABEL="省市"
		,COUNT(DISTINCT SORGCODE) AS ORG_CNT LABEL="机构数量"
		,SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END) AS LOAN_CNT LABEL="贷款业务数"
		,round(SUM(ICREDITLIMIT)/10000,0.01) AS LOAN_AMT LABEL="贷款金额"
		,round(SUM(IBALANCE)/10000,0.01) AS LOAN_BAL LABEL="贷款本金余额" 
		,COUNT(DISTINCT SPIN) AS CUST_CNT  LABEL="贷款客户数"
		,SUM(CASE WHEN IAMOUNTPASTDUE^=0 THEN 1 ELSE 0 END) AS OWE_CNT LABEL="逾期账户数"
		,round(SUM(IAMOUNTPASTDUE)/10000,0.01) AS OWE_AMT  LABEL="逾期总额"
		,COALESCE(A2.NEW_CUST_CNT,0)  AS NEW_CUST_CNT LABEL="新开客户数"
	FROM LOAN_N AS A1
		LEFT JOIN (
			SELECT
				ORGAREA
				,COUNT(DISTINCT SPIN) AS NEW_CUST_CNT
			FROM LOAN_N(WHERE=(IINFOINDICATOR=2)) 
			GROUP BY ORGAREA) AS A2
		ON A1.ORGAREA =A2.ORGAREA 
	GROUP BY A1.ORGAREA
	;
QUIT;
/*T-2月综合数据处理*/
PROC SQL;
	CREATE TABLE LOANAREA_O AS SELECT
		A1.ORGAREA LABEL="省市"
		,COUNT(DISTINCT SORGCODE) AS ORG_CNT LABEL="机构数量"
		,SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END) AS LOAN_CNT LABEL="贷款业务数"
		,SUM(ICREDITLIMIT)/10000 AS LOAN_AMT LABEL="贷款金额"
		,SUM(IBALANCE)/10000 AS LOAN_BAL LABEL="贷款本金余额" 
		,COUNT(DISTINCT SCERTNO) AS CUST_CNT  LABEL="贷款客户数"
		,SUM(CASE WHEN IAMOUNTPASTDUE^=0 THEN 1 ELSE 0 END) AS OWE_CNT LABEL="逾期账户数"
		,SUM(IAMOUNTPASTDUE)/10000 AS OWE_AMT  LABEL="逾期总额"
		,COALESCE(A2.NEW_CUST_CNT,0)  AS NEW_CUST_CNT LABEL="新开客户数"
	FROM LOAN_O AS A1
		LEFT JOIN (
			SELECT
				ORGAREA
				,COUNT(DISTINCT SCERTNO) AS NEW_CUST_CNT 
			FROM LOAN_O(WHERE=(IINFOINDICATOR=2)) 
			GROUP BY ORGAREA) AS A2
		ON A1.ORGAREA =A2.ORGAREA 
	GROUP BY A1.ORGAREA
	;
QUIT;

/*1.	D01不同省市发生贷款业务的机构分布情况表*/
PROC SQL;
	CREATE TABLE D01 AS SELECT
		A1.ORGAREA
		,A1.ORG_CNT AS ORG_CNT_N LABEL="库中当月累计机构数量"
		,COALESCE(A2.ORG_CNT,0) AS ORG_CNT_O LABEL="库中上月累计机构数量"
		,PUT(A1.ORG_CNT/A2.ORG_CNT-1,PERCENTN8.2) AS ORGADD_R LABEL="库中机构数量环比增长率"
	FROM LOANAREA_N AS A1
	LEFT JOIN LOANAREA_O AS A2
	ON A1.ORGAREA =A2.ORGAREA 
	ORDER BY ORG_CNT_N DESC,ORG_CNT_O DESC;
QUIT;
/*2.	D02不同省市的贷款账户及贷款金额分布情况表*/
PROC SQL;
	CREATE TABLE D02 AS SELECT
		A1.ORGAREA
		,A1.LOAN_CNT AS LOAN_CNT_N LABEL="库中当月累计贷款账户数"
		,COALESCE(A2.LOAN_CNT,0) AS LOAN_CNT_O LABEL="库中上月累计贷款账户数"
		,PUT(A1.LOAN_CNT/A2.LOAN_CNT-1,PERCENTN8.2) AS CNTADD_R LABEL="库中贷款账户数环比增长率"
		,ROUND(A1.LOAN_AMT,0.01) AS LOAN_AMT_N LABEL="库中当月累计贷款金额"
		,ROUND(COALESCE(A2.LOAN_AMT,0),0.01) AS LOAN_AMT_O LABEL="库中上月累计贷款金额"
		,PUT(A1.LOAN_AMT/A2.LOAN_AMT-1,PERCENTN8.2) AS AMTADD_R LABEL="库中贷款金额环比增长率"
		,ROUND(A1.LOAN_AMT/A1.LOAN_CNT,0.01) AS AVG_LOANAMT_N LABEL="当月账户平均贷款金额"
		,ROUND(A2.LOAN_AMT/A2.LOAN_CNT,0.01) AS AVG_LOANAMT_O LABEL="上月账户平均贷款金额"
	FROM LOANAREA_N AS A1
	LEFT JOIN LOANAREA_O AS A2
	ON A1.ORGAREA =A2.ORGAREA 
	ORDER BY LOAN_CNT_N DESC,LOAN_CNT_O DESC;
QUIT;
/*3.	D03不同省市的贷款客户数分布情况表*/
PROC SQL;
	CREATE TABLE D03 AS SELECT
		A1.ORGAREA
		,A1.CUST_CNT AS CUST_CNT_N LABEL="库中当月累计贷款客户数"
		,ROUND(A1.LOAN_CNT/A1.CUST_CNT,0.01) AS AVG_LOAN_CNT_N  LABEL="库中当月每客户平均账户数"
		,COALESCE(A2.CUST_CNT,0) AS CUST_CNT_O LABEL="库中上月累计贷款客户数"
		,ROUND(A2.LOAN_CNT/A2.CUST_CNT,0.01) AS AVG_LOAN_CNT_O  LABEL="库中上月每客户平均账户数"
		,PUT(A1.CUST_CNT/A2.CUST_CNT-1,PERCENTN8.2) AS CUSTADD_R LABEL="库中贷款客户数环比增长率"
	FROM LOANAREA_N AS A1
	LEFT JOIN LOANAREA_O AS A2
	ON A1.ORGAREA =A2.ORGAREA 
	ORDER BY CUST_CNT_N DESC,CUST_CNT_O DESC;
QUIT;

/*4.	D04不同省市的贷款逾期账户及逾期金额分布情况表*/
PROC SQL;
	CREATE TABLE D04 AS SELECT
		A1.ORGAREA
		,A1.LOAN_CNT AS LOAN_CNT_N LABEL="库中当月累计贷款账户数"
		,A1.OWE_CNT AS OWE_CNT_N LABEL="库中当月累计逾期账户数"
		,PUT(A1.OWE_CNT/A1.LOAN_CNT,PERCENTN8.2) AS OWECNT_R LABEL="逾期账户数占总账户数比例"
		,ROUND(A1.LOAN_AMT,0.01) AS LOAN_AMT_N LABEL="库中当月累计贷款金额"
		,ROUND(A1.OWE_AMT,0.01) AS OWE_AMT_N LABEL="库中当月累计逾期金额"
		,PUT(A1.OWE_AMT/A1.LOAN_AMT,PERCENTN8.2) AS OWEAMT_R LABEL="逾期金额占贷款金额比例"
		,ROUND(A1.LOAN_AMT/A1.LOAN_CNT,0.01) AS AVG_LOANAMT_N  LABEL="当月账户平均贷款金额"
		,ROUND(A1.OWE_AMT/A1.OWE_CNT,0.01) AS AVG_OWEAMT_N  LABEL="当月账户平均逾期金额"
	FROM LOANAREA_N AS A1
	ORDER BY LOAN_CNT_N DESC,OWE_CNT_N DESC;
QUIT;

/*5.	D05不同省市的贷款新开客户数分布情况表*/
/*PROC SQL;*/
/*	CREATE TABLE D05 AS SELECT*/
/*		A1.ORGAREA*/
/*		,A1.NEW_CUST_CNT AS NEW_CNT_N LABEL="库中当月累计新开客户数"*/
/*		,PUT(A1.NEW_CUST_CNT/A1.CUST_CNT,PERCENTN8.2) AS NEWCNT_R_N LABEL="当月新开客户数占总客户数比例"*/
/*		,COALESCE(A2.NEW_CUST_CNT,0) AS NEW_CNT_O LABEL="库中上月累计新开客户数"*/
/*		,PUT(A2.NEW_CUST_CNT/A2.CUST_CNT,PERCENTN8.2) AS NEWCNT_R_O LABEL="上月新开客户数占总客户数比例"*/
/*		,PUT(A1.NEW_CUST_CNT/A2.NEW_CUST_CNT-1,PERCENTN8.2) AS NEWCNTADD_R LABEL="库中新开客户数环比增长率"*/
/*	FROM LOANAREA_N AS A1*/
/*	LEFT JOIN LOANAREA_O AS A2*/
/*	ON A1.ORGAREA =A2.ORGAREA */
/*	ORDER BY NEW_CNT_N DESC;*/
/*	DELETE FROM D05 WHERE NEW_CNT_N=0;*/
/*QUIT;*/

/*6.	D06不同省市的贷款申请数及申请金额分布情况表*/

PROC SQL;
	CREATE TABLE D06 AS SELECT
		A1.ORGAREA LABEL="省市"
		,A1.APPLY_CNT_N LABEL="库中当月累计贷款申请数"
		,COALESCE(A2.APPLY_CNT_O,0) LABEL="库中上月累计贷款申请数"
		,PUT(A1.APPLY_CNT_N/A2.APPLY_CNT_O-1,PERCENTN8.2) AS APPLYADD_R LABEL="库中贷款申请数环比增长率"
		,ROUND(A1.APPLY_AMT_N,0.01) AS APPLY_AMT_N LABEL="库中当月累计贷款申请金额"
		,COALESCE(ROUND(A2.APPLY_AMT_O,0.01),0) AS APPLY_AMT_O LABEL="库中上月累计贷款申请金额"
		,PUT(A1.APPLY_AMT_N/A2.APPLY_AMT_O-1,PERCENTN8.2) AS APPLYAMTADD_R LABEL="库中贷款申请金额环比增长率"
		,ROUND(A1.APPLY_AMT_N/A1.APPLY_CNT_N,0.01) AS AVG_APPLYAMT_N LABEL="当月账户平均申请金额"
		,ROUND(A2.APPLY_AMT_O/A2.APPLY_CNT_O,0.01) AS AVG_APPLYAMT_O LABEL="上月账户平均申请金额"
	FROM (
		SELECT
			ORGAREA
			,SUM(CASE WHEN SAPPLYCODE^="" THEN 1 ELSE 0 END) AS APPLY_CNT_N LABEL="贷款申请业务数"
			,SUM(IMONEY)/10000 AS APPLY_AMT_N LABEL="贷款申请总额"
		FROM APPLY_N 
		GROUP BY ORGAREA) AS A1
	LEFT JOIN (
		SELECT
			ORGAREA
			,SUM(CASE WHEN SAPPLYCODE^="" THEN 1 ELSE 0 END) AS APPLY_CNT_O LABEL="贷款申请业务数"
			,SUM(IMONEY)/10000 AS APPLY_AMT_O LABEL="贷款申请总额"
		FROM APPLY_O 
		GROUP BY ORGAREA) AS A2
	ON A1.ORGAREA=A2.ORGAREA
	ORDER BY APPLY_CNT_N DESC,APPLY_CNT_O DESC;
QUIT;

/*7.	D07不同省市的特殊交易业务数及特殊交易金额分布情况表*/
PROC SQL;
	CREATE TABLE D07 AS SELECT
		A1.ORGAREA LABEL="省市"
		,A1.SPEC_CNT_N LABEL="库中当月累计特殊交易业务数"
		,COALESCE(A2.SPEC_CNT_O,0) LABEL="库中上月累计特殊交易业务数"
		,PUT(A1.SPEC_CNT_N/A2.SPEC_CNT_O-1,PERCENTN8.2) AS SPECADD_R LABEL="库中特殊交易业务数环比增长率"
		,ROUND(A1.SPEC_AMT_N,0.01) AS SPEC_AMT_N LABEL="库中当月累计特殊交易金额"
		,COALESCE(ROUND(A2.SPEC_AMT_O,0.01),0) AS SPEC_AMT_O LABEL="库中上月累计特殊交易金额"
		,PUT(A1.SPEC_AMT_N/A2.SPEC_AMT_O-1,PERCENTN8.2) AS SPECAMTADD_R LABEL="库中特殊交易金额环比增长率"
		,ROUND(A1.SPEC_AMT_N/A1.SPEC_CNT_N,0.01) AS AVG_APPLYAMT_N LABEL="当月平均特殊交易金额"
		,ROUND(A2.SPEC_AMT_O/A2.SPEC_CNT_O,0.01) AS AVG_APPLYAMT_O LABEL="上月平均特殊交易金额"
	FROM (
		SELECT
			ORGAREA
			,SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END) AS SPEC_CNT_N LABEL="库中当月累计特殊交易业务数"
			,SUM(IOCCURSUM)/10000 AS SPEC_AMT_N LABEL="库中当月累计特殊交易金额"
		FROM SPEC_N 
		GROUP BY ORGAREA) AS A1
	LEFT JOIN (
		SELECT
			ORGAREA
			,SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END) AS SPEC_CNT_O LABEL="库中上月累计特殊交易业务数"
			,SUM(IOCCURSUM)/10000 AS SPEC_AMT_O LABEL="库中上月累计特殊交易金额"
		FROM SPEC_O 
		GROUP BY ORGAREA) AS A2
	ON A1.ORGAREA=A2.ORGAREA
	ORDER BY SPEC_CNT_N DESC,SPEC_CNT_O DESC,SPEC_AMT_N DESC;
QUIT;

/*8.	D08不同省市的特殊交易客户数分布情况表*/
PROC SQL;
	CREATE TABLE D08 AS SELECT
		A1.ORGAREA LABEL="省市"
		,A1.CUST_CNT_N LABEL="库中当月累计特殊交易客户数"
		,A1.AVG_SPEC_N LABEL="库中当月平均客户赖账数"
		,A2.CUST_CNT_O LABEL="库中上月累计特殊交易客户数"
		,A2.AVG_SPEC_O LABEL="库中上月平均客户赖账数"
		,PUT(A1.CUST_CNT_N/A2.CUST_CNT_O-1,PERCENTN8.2) AS SPECAMTADD_R LABEL="库中特殊交易环比增长率"
	FROM (
		SELECT
			ORGAREA
			,COUNT(DISTINCT SCERTNO) AS CUST_CNT_N LABEL="库中当月累计特殊交易客户数"
			,ROUND(SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END)/COUNT(DISTINCT SCERTNO),0.01) AS AVG_SPEC_N LABEL="库中当月平均客户赖账数"
		FROM SPEC_N 
		GROUP BY ORGAREA) AS A1
	LEFT JOIN (
		SELECT
			ORGAREA
			,COUNT(DISTINCT SCERTNO) AS CUST_CNT_O LABEL="库中当月累计特殊交易客户数"
			,ROUND(SUM(CASE WHEN SACCOUNT^="" THEN 1 ELSE 0 END)/COUNT(DISTINCT SCERTNO),0.01) AS AVG_SPEC_O LABEL="库中当月平均客户赖账数"
		FROM SPEC_O 
		GROUP BY ORGAREA) AS A2
	ON A1.ORGAREA=A2.ORGAREA
	ORDER BY CUST_CNT_N DESC,CUST_CNT_O DESC;
QUIT;

PROC SQL;
	DROP TABLE  LOAN_N,LOAN_N1,LOAN_N2,LOAN_O,LOAN_O1,LOAN_O2,APPLY_N,APPLY_N1,APPLY_N2,APPLY_O,APPLY_O1,APPLY_O2,SPEC_N1,SPEC_N2,SPEC_N
	,SPEC_O1,SPEC_O2,SPEC_O,LOANAREA_N,LOANAREA_O	;
QUIT;

/*结果数据导出*/
LIBNAME MYXLS EXCEL &OUTPATH_D01.;
DATA MYXLS."D01机构分布情况表"n(dblabel=YES);
	SET D01;
RUN;
DATA MYXLS."D02贷款账户分布情况表"n(dblabel=YES);
	SET D02;
RUN;
DATA MYXLS."D03贷款客户分布情况表"n(dblabel=YES);
	SET D03;
RUN;
DATA MYXLS."D04逾期账户分布情况表"n(dblabel=YES);
	SET D04;
RUN;
DATA MYXLS."D05新开客户分布情况表"n(dblabel=YES);
	SET D05;
RUN;
DATA MYXLS."D06贷款申请分布情况表"n(dblabel=YES);
	SET D06;
RUN;
DATA MYXLS."D07特殊交易分布情况表"n(dblabel=YES);
	SET D07;
RUN;
DATA MYXLS."D08特殊交易客户分布情况表"n(dblabel=YES);
	SET D08;
RUN;
LIBNAME MYXLS CLEAR;

%MEND AREA_ANALYSIS;

